version: '3.8'

services:
  kanata:
    build: .
    container_name: kanata-bot
    restart: unless-stopped
    ports:
      - "3000:3000" 
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
